### ISSUE TITLE
调整splash ad出现方式

### ISSUE THREAD

**Issue by easonccc1** [haxibiao/react-native-ad#10]
你好，我用android splash ad。能够正常显示。

用户打开app后，显示顺序是：我的开机screen1 -> splash ad screen. 

但是splash ad screen是从右边滑入屏幕。请问是否能调整splash ad screen出现方式？比如，直接展现，而不是从左右上下滑入。

**Comment by PBK-B** [comment]
@easonccc1 好的，计划下次开放预留调整接口

**Comment by PBK-B** [comment]
> 你好，我用android splash ad。能够正常显示。
> 
> 用户打开app后，显示顺序是：我的开机screen1 -> splash ad screen.
> 
> 但是splash ad screen是从右边滑入屏幕。请问是否能调整splash ad screen出现方式？比如，直接展现，而不是从左右上下滑入。

@easonccc1 将 react-native-ad 升级到 1.1.4 版本之后，参考 splash_anim 文档即可更换 android 开屏广告动画效果，相关文档已经更新：[splash_anim.md](https://github.com/haxibiao/react-native-ad/blob/master/docs/splash_anim.md)
