### ISSUE TITLE
android-头条信息流广告问题

### ISSUE THREAD

**Issue by easonccc1** [haxibiao/react-native-ad#13]
如下面的截图，会直接红屏，显示找不到width。

Android studio的logcat结果：

`2021-03-11 07:30:01.175 18272-18272/com.xx.xxx E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by Timing
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.core.TimingModule.access$000(TimingModule.java:22)
        at com.facebook.react.modules.core.TimingModule$BridgeTimerManager.callTimers(TimingModule.java:28)
        at com.facebook.react.modules.core.JavaTimerManager$TimerFrameCallback.doFrame(JavaTimerManager.java:84)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

我的代码：

```
<View
      style={{
        height: windowWidth/1.5,
        width: windowWidth,
      }}
    >
      <ad.Feed
        codeid={codeid}
        adWidth={adWidth}
        onAdLayout={(data) => {
          console.log('Feed 广告加载成功！', data);
      }}
      onAdClose={(data) => {
        console.log('Feed 广告关闭！', data);
      }}
      onAdError={(err) => {
        console.log('Feed 广告加载失败！', err);
      }}
      onAdClick={(val) => {
        console.log('Feed 广告被用户点击！', val);
      }}
    />;
</View>```

ios测过了，没有问题。就是android有问题，虚拟机和真机都测过。
<img width="311" alt="Screen Shot 2021-03-11 at 7 28 59 AM" src="https://user-images.githubusercontent.com/29586734/110713136-59bae000-823c-11eb-9d89-7b51ec0b8526.png">

**Comment by easonccc1** [comment]
<img width="311" alt="Screen Shot 2021-03-11 at 7 28 59 AM" src="https://user-images.githubusercontent.com/29586734/110716308-d8664c00-8241-11eb-878f-a9f69129378e.png">

**Comment by PBK-B** [comment]
@easonccc1 我们这边跑一切正常问题应该不是在 ad.Feed View 上，你是不是使用了 ```ad.loadFeedAd(appid,codeid);``` 预加载广告？看看你这部分预加载广告的代码

**Comment by easonccc1** [comment]
预加载的代码跟readme是一致的，就在页面的componentDidMount()里调用了一次。

```
ad.loadFeedAd({
      appid: appid,
      codeid: codeid,
    }).then(
      (result) => {
        console.log('load feed ad result ', result);
      },
      (reason) => {
        console.log('加载 feed ad 失败理由 ', reason);
      }
    );
```

我把这个预加载的代码注销掉了，android就没问题，可以显示feed ad了。不清楚是什么原因。

一般来说，这个预加载是否一定必须呢？

**Comment by PBK-B** [comment]
> 预加载的代码跟readme是一致的，就在页面的componentDidMount()里调用了一次。
> 
> ```
> ad.loadFeedAd({
>       appid: appid,
>       codeid: codeid,
>     }).then(
>       (result) => {
>         console.log('load feed ad result ', result);
>       },
>       (reason) => {
>         console.log('加载 feed ad 失败理由 ', reason);
>       }
>     );
> ```
> 
> 我把这个预加载的代码注销掉了，android就没问题，可以显示feed ad了。不清楚是什么原因。
> 
> 一般来说，这个预加载是否一定必须呢？

这个预加载不是必须的，预加载的话是可以在 App 启动时就将部分广告加载好，广告展示的时候可能就会直接展示。用户体验会得到提升

**Comment by PBK-B** [comment]
@easonccc1 你 react-native 版本多少的呀？

**Comment by easonccc1** [comment]
> @easonccc1 你 react-native 版本多少的呀？

"react-native": "0.63.4",

**Comment by easonccc1** [comment]
> > 预加载的代码跟readme是一致的，就在页面的componentDidMount()里调用了一次。
> > ```
> > ad.loadFeedAd({
> >       appid: appid,
> >       codeid: codeid,
> >     }).then(
> >       (result) => {
> >         console.log('load feed ad result ', result);
> >       },
> >       (reason) => {
> >         console.log('加载 feed ad 失败理由 ', reason);
> >       }
> >     );
> > ```
> > 
> > 
> > 我把这个预加载的代码注销掉了，android就没问题，可以显示feed ad了。不清楚是什么原因。
> > 一般来说，这个预加载是否一定必须呢？
> 
> 这个预加载不是必须的，预加载的话是可以在 App 启动时就将部分广告加载好，广告展示的时候可能就会直接展示。用户体验会得到提升

明白了，那如果我有3个信息流广告，岂不是都在app launch的时候，预加载？

这个在app launch预加载的机制，是否也适用于app中所有的广告类型？

**Comment by PBK-B** [comment]
> > > 预加载的代码跟readme是一致的，就在页面的componentDidMount()里调用了一次。
> > > ```
> > > ad.loadFeedAd({
> > >       appid: appid,
> > >       codeid: codeid,
> > >     }).then(
> > >       (result) => {
> > >         console.log('load feed ad result ', result);
> > >       },
> > >       (reason) => {
> > >         console.log('加载 feed ad 失败理由 ', reason);
> > >       }
> > >     );
> > > ```
> > > 
> > > 
> > > 我把这个预加载的代码注销掉了，android就没问题，可以显示feed ad了。不清楚是什么原因。
> > > 一般来说，这个预加载是否一定必须呢？
> > 
> > 
> > 这个预加载不是必须的，预加载的话是可以在 App 启动时就将部分广告加载好，广告展示的时候可能就会直接展示。用户体验会得到提升
> 
> 明白了，那如果我有3个信息流广告，岂不是都在app launch的时候，预加载？
> 
> 这个在app launch预加载的机制，是否也适用于app中所有的广告类型？

大部分广告都预留了预加载的使用方式，具体可以参考一下文档，如果有其他需求可以提出来

**Comment by PBK-B** [comment]
@easonccc1 你可以删除之前的 react-native-ad 包然后更新一下 react-native-ad 包，试试以下代码是否还报错
```
    // 提前加载feed ad 结果测试
    ad.loadFeedAd({
      appid: '000000',
      codeid: '000000000',
      adWidth: '400',
    }).then(
      (result) => {
        console.log('load feed ad result ', result);
      },
      (reason) => {
        console.log('加载 feed ad 失败理由 ', reason);
      },
    );
```

**Comment by easonccc1** [comment]
> @easonccc1 你可以删除之前的 react-native-ad 包然后更新一下 react-native-ad 包，试试以下代码是否还报错
> 
> ```
>     // 提前加载feed ad 结果测试
>     ad.loadFeedAd({
>       appid: '000000',
>       codeid: '000000000',
>       adWidth: '400',
>     }).then(
>       (result) => {
>         console.log('load feed ad result ', result);
>       },
>       (reason) => {
>         console.log('加载 feed ad 失败理由 ', reason);
>       },
>     );
> ```

也试过了，把预加载放在app启动，直接就把开屏卡住了。没办法，只能直接删除预加载了。

**Comment by PBK-B** [comment]
> > @easonccc1 你可以删除之前的 react-native-ad 包然后更新一下 react-native-ad 包，试试以下代码是否还报错
> > ```
> >     // 提前加载feed ad 结果测试
> >     ad.loadFeedAd({
> >       appid: '000000',
> >       codeid: '000000000',
> >       adWidth: '400',
> >     }).then(
> >       (result) => {
> >         console.log('load feed ad result ', result);
> >       },
> >       (reason) => {
> >         console.log('加载 feed ad 失败理由 ', reason);
> >       },
> >     );
> > ```
> 
> 也试过了，把预加载放在app启动，直接就把开屏卡住了。没办法，只能直接删除预加载了。

新项目对接也是如此吗？

**Comment by easonccc1** [comment]
1.1.4 release的代码中，解码方法是在loadFeedAd（）加入width。

ad.loadFeedAd({
      appid: this.appId,
      codeid: this.adUnitId,
      width: width,
}

这个是在doc里没有提到的。

**Comment by PBK-B** [comment]
> 1.1.4 release的代码中，解码方法是在loadFeedAd（）加入width。
> 
> ad.loadFeedAd({
> appid: this.appId,
> codeid: this.adUnitId,
> width: width,
> }
> 
> 这个是在doc里没有提到的。

好的，感谢提醒。我更新一下文档
