### ISSUE TITLE
android FullVideoAd 会先展示一个白屏

### ISSUE THREAD

**Issue by easonccc1** [haxibiao/react-native-ad#14]
应该是如下代码：

https://github.com/haxibiao/react-native-ad/blob/master/android/src/main/java/com/haxifang/ad/activities/FullScreenActivity.java#L33

不清楚为什么要先渲染个白屏，为了缓冲？
但是是否弄成黑屏会好一点，因为视频广告提前缓冲好后，准备播放时候，系统默认是一段黑屏。

所以现在是 白屏 -> 播放器加载黑屏 -> 播放广告

建议改成：黑屏 -> 播放器加载黑屏 -> 播放广告

**Comment by PBK-B** [comment]
@easonccc1 已经同步最新代码并更新了包，您可以目前已经按照需求完成调整，可以将尝试更新使用，再次感谢您的建议以及反馈
