### ISSUE TITLE
splash ad是否能提供onLoad() event listener?

### ISSUE THREAD

**Issue by easonccc1** [haxibiao/react-native-ad#16]
当前splash ad没有 onLoad() callback。

如果按当前逻辑展示：app本身开屏界面（不包含ad） -> react-native-ad splash ad界面（开始load ad） -> app主界面.

问题在于假如第二步没有及时load或者load error，那么第二个界面就是白屏。

是否能提供onLoad() callback，这样逻辑改成：

app本身开屏界面（不包含ad):
* 假如splash ad load成功, 展示react-native-ad splash ad界面 -> app主界面;
* 假如splash ad load失败, 直接app主界面

**Comment by PBK-B** [comment]
> 当前splash ad没有 onLoad() callback。
> 
> 如果按当前逻辑展示：app本身开屏界面（不包含ad） -> react-native-ad splash ad界面（开始load ad） -> app主界面.
> 
> 问题在于假如第二步没有及时load或者load error，那么第二个界面就是白屏。
> 
> 是否能提供onLoad() callback，这样逻辑改成：
> 
> app本身开屏界面（不包含ad):
> 
> * 假如splash ad load成功, 展示react-native-ad splash ad界面 -> app主界面;
> * 假如splash ad load失败, 直接app主界面

目前的逻辑是先启动 splash ad 界面再 load 广告的，也就是说无论 load 是否成功都必须先启动 splash ad 界面。
如果需要实现你所提到的这个功能我目前想到有两种解决思路：
1，添加 splash ad 的预加载功能
2，增加 onLoad 监听和 close 主动关闭开屏广告方法

按照你上面所描述的话，似乎第 1 种方案更适合。
不过考虑到用户体验的话，我想的是会不会出现 App 已经启动完成了，这时候如果触发了  splash ad 的预加载完成然后突然跳出一个开屏广告…
所以我认为先提供一个 close 主动关闭开屏广告方法较为可靠，不过还是可能会出现一瞬间的白屏闪过的情况。

**Comment by easonccc1** [comment]
`1，添加 splash ad 的预加载功能`

这个方法确实是比较好。

`不过考虑到用户体验的话，我想的是会不会出现App 已经启动完成了，这时候如果触发了 splash ad 的预加载完成然后突然跳出一个开屏广告…` 

这个一般来说，我的处理逻辑是，app启动，然后等3s。只要是3s以内，splash ad预加载好了，就可以直接展示了。如果>3s还没有load成功，那就直接不展示splash，调到主页面。

**Comment by PBK-B** [comment]
> `1，添加 splash ad 的预加载功能`
> 
> 这个方法确实是比较好。
> 
> `不过考虑到用户体验的话，我想的是会不会出现App 已经启动完成了，这时候如果触发了 splash ad 的预加载完成然后突然跳出一个开屏广告…`
> 
> 这个一般来说，我的处理逻辑是，app启动，然后等3s。只要是3s以内，splash ad预加载好了，就可以直接展示了。如果>3s还没有load成功，那就直接不展示splash，调到主页面。

收到，那我们这边先尝试做一个 splash ad 预加载功能

**Comment by easonccc1** [comment]
感谢。如果要实现的话，一点小建议就是 react-native-ad不要自己实现这个"3秒“控制逻辑。这个还是交给我们自己处理就好了。

**Comment by PBK-B** [comment]
@easonccc1 使用 `ad.init()` 方法，传入 `codeid_splash` 参数。参考代码：<https://github.com/haxibiao/react-native-ad/blob/master/example/src/Splash.js#L9>
