### ISSUE TITLE
请问banner什么时候ready？

### ISSUE THREAD

**Issue by xeqd** [haxibiao/react-native-ad#17]
rt

**Comment by PBK-B** [comment]
@xeqd Banner 广告样式已经在开发计划中了

**Comment by surethink** [comment]
> @xeqd Banner 广告样式已经在开发计划中了

期待，有计划上线时间了没

**Comment by PBK-B** [comment]
@xeqd @surethink 全新的穿山甲已推荐对接聚合 GroMore 广告 SDK，我们已经在 React Native 中完成 GroMore 全部广告类型的对接以及 RN 新旧架构，访问 http://docs.ads.zmkj6.top 可查看 react-native-gromore 对接文档，也可以通过 联系我们 获得源码。
