### ISSUE TITLE
哪里能知道toutiao fullVideo ad预加载已经成功？

### ISSUE THREAD

**Issue by easonccc1** [haxibiao/react-native-ad#19]
https://github.com/haxibiao/react-native-ad/blob/master/example/src/FullScreenVideo.js

fullVideo ad预加载是通过ad.init({codeid_full_video}), 但是我发现就算加载成功，也不会调用如下onAdLoaded()

```
let fullVideo = ad.startFullVideo({appid,codeid});
fullVideo.subscribe('onAdLoaded', (event) => {
  console.log('广告加载成功监听', event);
});
```

是否能够ad.init({codeid_full_video})预加载成功后，调用某个callback呢？或者在哪里能知道这个fullVideo ad是否已经加载成功？

**Comment by PBK-B** [comment]
@easonccc1 知道预加载成功是有什么需求嘛？一般来说如果预加载成功的话第一次启动 fullVideo ad 的话就会使用预加载的广告的
