### ISSUE TITLE
激励视频中途出错，关闭后返回结果video_play是true

### ISSUE THREAD

**Issue by yinMrsir** [haxibiao/react-native-ad#3]
[Fri Aug 14 2020 15:27:47.772]  LOG      广告加载成功监听 {"code": 200, "message": "视频广告的素材加载完毕"}
[Fri Aug 14 2020 15:27:49.164]  LOG      广告加载成功监听 {"code": 202, "message": "开始展示奖励视频"}
[Fri Aug 14 2020 15:28:02.457]  LOG      广告加载失败监听 {"code": 1004, "message": "激励视频播放出错了"}
[Fri Aug 14 2020 15:28:02.470]  LOG      广告加载失败监听 {"code": 1004, "message": "激励视频播放出错了"}
[Fri Aug 14 2020 15:28:02.476]  LOG      广告加载失败监听 {"code": 1004, "message": "激励视频播放出错了"}
[Fri Aug 14 2020 15:28:02.495]  LOG      广告加载失败监听 {"code": 1004, "message": "激励视频播放出错了"}
[Fri Aug 14 2020 15:28:02.713]  LOG      广告加载失败监听 {"code": 1004, "message": "激励视频播放出错了"}
[Fri Aug 14 2020 15:28:08.157]  LOG      广告被关闭监听 {"code": 204, "message": "关闭激励视频"}
[Fri Aug 14 2020 15:28:08.186]  LOG      RewardVideo 回调结果 {"video_play":true,"ad_click":false,"apk_install":false,"verify_status":false}

**Comment by PBK-B** [comment]
@yinMrsir video_play 好像是激励视频开始播放标识…
