### ISSUE TITLE
这个库最近还更新吗，android跑不起来，ios加载广告失败

### ISSUE THREAD

**Issue by Miluaaa** [haxibiao/react-native-ad#30]
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.pangle.cn:ads-sdk:3.9.0.5.
     Searched in the following locations:
       - file:/Users/milu/.m2/repository/com/pangle/cn/ads-sdk/3.9.0.5/ads-sdk-3.9.0.5.pom
       - file:/Users/milu/Documents/Project/jiashuntong/node_modules/react-native/android/com/pangle/cn/ads-sdk/3.9.0.5/ads-sdk-3.9.0.5.pom
       - file:/Users/milu/Documents/Project/jiashuntong/node_modules/jsc-android/dist/com/pangle/cn/ads-sdk/3.9.0.5/ads-sdk-3.9.0.5.pom
       - https://dl.google.com/dl/android/maven2/com/pangle/cn/ads-sdk/3.9.0.5/ads-sdk-3.9.0.5.pom
       - https://jcenter.bintray.com/com/pangle/cn/ads-sdk/3.9.0.5/ads-sdk-3.9.0.5.pom
       - https://www.jitpack.io/com/pangle/cn/ads-sdk/3.9.0.5/ads-sdk-3.9.0.5.pom
       - file:/Users/milu/Documents/Project/jiashuntong/node_modules/@0x5e/react-native-alipay/android/libs/ads-sdk-3.9.0.5.jar
       - file:/Users/milu/Documents/Project/jiashuntong/node_modules/@0x5e/react-native-alipay/android/libs/ads-sdk.jar
       - file:/Users/milu/Documents/Project/jiashuntong/android/app/libs/ads-sdk-3.9.0.5.jar
       - file:/Users/milu/Documents/Project/jiashuntong/android/app/libs/ads-sdk.jar
       - file:/Users/milu/Documents/Project/jiashuntong/node_modules/react-native-ali-onepass/android/libs/ads-sdk-3.9.0.5.jar
       - file:/Users/milu/Documents/Project/jiashuntong/node_modules/react-native-ali-onepass/android/libs/ads-sdk.jar
     Required by:
         project :app > project :react-native-ad

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by guairongyi** [comment]
散了吧！编译不过去的

**Comment by PBK-B** [comment]
@Miluaaa @guairongyi 目前穿山甲已推荐对接聚合 GroMore 广告 SDK，我们已经在 React Native 中完成 GroMore 全部广告类型的对接以及 RN 新旧架构，访问 http://docs.ads.zmkj6.top/ 可查看 react-native-gromore 对接文档，也可以通过 [联系我们](https://github.com/haxibiao/react-native-ad#%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC-) 获得源码。
