### ISSUE TITLE
为什么没有banner广告了呢？

### ISSUE THREAD

**Issue by qew4** [haxibiao/react-native-ad#31]
为什么没有banner广告了呢？这是一个很好的插件

**Comment by PBK-B** [comment]
@qew4 我们在 react-native-gromore 已经支持上 banner 广告类型，目前穿山甲已推荐对接聚合 GroMore 广告 SDK，我们已经在 React Native 中完成 GroMore 全部广告类型的对接以及 RN 新旧架构，访问 http://docs.ads.zmkj6.top/ 可查看 react-native-gromore 对接文档，也可以通过 [联系我们](https://github.com/haxibiao/react-native-ad#%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC-) 获得源码。
