### ISSUE TITLE
激励视频预加载提示申请的代码位广告类型和代码中使用的广告类型接口不一致

### ISSUE THREAD

**Issue by yinMrsir** [haxibiao/react-native-ad#4]
[Error: feed ad error媒体在平台上申请的代码位广告类型和代码中使用的广告类型接口不一致。例如平台上是开屏的广告类型，但是代码中请求的接口是banner或者其他非开屏的广告类型，如果不太清楚不同代码
位类型对应的接口，麻烦去查询SDK包里的对接文档。]

运行了下**示例代码也有此类问题**

**Comment by PBK-B** [comment]
@yinMrsir android 还是 ios 呢？方便提供更多相关的信息吗？
