### ISSUE TITLE
良心项目-兄弟来个捐赠二维码

### ISSUE THREAD

**Issue by huyanping** [haxibiao/react-native-ad#6]

**Comment by xugengning** [comment]
兄弟,引入成功了吗

**Comment by xugengning** [comment]
一直pod install不过

**Comment by kangfenmao** [comment]
支持良心项目 ❤️

**Comment by PBK-B** [comment]
感谢大家的支持，你们的支持就是我们团队维护的动力

**Comment by PBK-B** [comment]
@huyanping  @kangfenmao 首先感谢你们的支持，目前该包的维护几乎陷入停滞，希望大家有能力的能够支持一下。以下是我们的联系方式 <https://github.com/haxibiao/react-native-ad#%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC->
