### ISSUE TITLE
插屏广告要如何接入

### ISSUE THREAD

**Issue by xugengning** [haxibiao/react-native-ad#7]
插屏广告要如何接入

**Comment by PBK-B** [comment]
插屏广告用到好像比较少…体验也不是很好吧，可以试试用 Banner 广告代替一下？

**Comment by PBK-B** [comment]
@xugengning 目前已经在开发的计划中了，感谢您的关注

**Comment by PBK-B** [comment]
@xugengning 穿山甲新插屏广告对接，v1.1.7 已经更新：https://github.com/haxibiao/react-native-ad/tree/master/docs#%E5%85%A8%E5%B1%8F%E8%A7%86%E9%A2%91%E6%96%B0%E6%8F%92%E5%B1%8F%E5%B9%BF%E5%91%8Afullvideo%E5%B9%BF%E5%91%8A%E7%9A%84%E5%AF%B9%E6%8E%A5%E5%8F%8A%E7%A4%BA%E4%BE%8B
