### ISSUE TITLE
splash ad， onAdShow()没有用

### ISSUE THREAD

**Issue by easonccc1** [haxibiao/react-native-ad#9]
splashAd.subscribe('onAdShow', (e) => {
      console.log('splashad onAdShow', e);
    });

这个callback一直没有被调用。

**Comment by PBK-B** [comment]
@easonccc1 android 和 IOS 都拿不到回调吗？

**Comment by easonccc1** [comment]
> @easonccc1 android 和 IOS 都拿不到回调吗？

我的是android。ios不确定。
